name: Test Workflow

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      message:
        description: 'Test message'
        required: false
        default: 'Manual workflow run'

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Show environment
        run: |
          echo "Running on a self-hosted runner"
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"
          
      - name: Simulate private resource access
        run: |
          echo "This step would access private resources"
          echo "Current directory: $(pwd)"
          ls -la
          
      - name: Run tests
        run: |
          echo "Running tests on the example app..."
          python test_app.p
